  version: "3"

  services:
    api:
      build: ./api
      ports:
      - 8080:8080
      container_name: api

    client:
      build: ./client
      ports: 
        - 3000:3000
      container_name: client

    db:
      image: mongo:4
      ports:
        - "27017:27017"
      container_name: db